import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { sample_games, RtaMatch } from "@/data/sample_data";
import Link from "next/link";

type MatchHistoryProps = {
  sample_games: RtaMatch[];
};

export async function getServerSideProps() {
  return {
    props: {
      sample_games,
    },
  };
}

export default function MatchHistory({ sample_games }: MatchHistoryProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <Link href={"/"} className="text-3xl font-bold underline">
              Go back to main page
            </Link>
            <h1 className="text-3xl font-bold underline">Sample Matches</h1>
            {sample_games.map((rta_match: RtaMatch) => (
              <div className="p-5" key={rta_match.uid}>
                <h6>Player 1: {rta_match.players[0]}</h6>
                <h6>Player 2: {rta_match.players[1]}</h6>
                <h6>
                  First Pick:{" "}
                  {rta_match.first_pick
                    ? rta_match.players[0]
                    : rta_match.players[1]}
                </h6>
                <h5 className="mt-2">Draft:</h5>
                <div className="flex">
                  <ul className="px-2">
                    {rta_match.picks.slice(0, 5).map((pick) => (
                      <li key={pick}>{pick}</li>
                    ))}
                  </ul>
                  <ul className="px-2">
                    {rta_match.picks.slice(5, 10).map((pick) => (
                      <li key={pick}>{pick}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
